# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ikramul Alam
email: ikram.tanjib@gmail.com
description: >
  #!/usr/bin/python
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tanjibpa.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Ikramul Alam'
bio: >
  An ordinary python enthusiast and Linux fan. 

author_image: "/assets/images/tan.jpg"
twitter_username: IkramulA
github_username:  tanjibpa

# Build settings
markdown: kramdown

timezone: "Asia/Dhaka"

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
